global:
  image: node:14
  trigger:
    branch:
      - testnet
  environment:
    APP_ENV: testnet

jobs:
  - name: build
    commands:
      - npm ci
      - npm run generate
      - rm ./dist/CNAME && mv ./dist/CNAME_TESTNET ./dist/CNAME
    artifacts:
      - name: dist

  - name: alpine/git
    work-dir: /app
    secrets:
      - GH_DEPLOY_KEY_TESTNET
    commands:
      - mkdir -p /root/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - echo $GH_DEPLOY_KEY_TESTNET | base64 -d > /root/.ssh/id_rsa
      - chmod 400 /root/.ssh/id_rsa
      - cd dist
      - git init
      - git add -A
      - git config --local user.name "Effect Network"
      - git config --local user.email "ops@effect.ai"
      - git commit -m "deploy"
      - ls -lha .git
      - git push -f git@github.com:effectai/force-frontend-testnet.git master:gh-pages
    resources:
      - name: dist
